import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Auto-generated by docusaurus-plugin-typedoc on build.
const typedocSidebar = require('./docs/api/typedoc-sidebar.cjs');

const sidebars: SidebarsConfig = {
  guides: [
    'index',
    'getting-started',
    'realtime-data',
    'historical-candles',
    'trading',
  ],
  api: [
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api/index'},
      items: typedocSidebar.items ?? typedocSidebar,
    },
  ],
};

export default sidebars;
